### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by InfinitePower563** [InfinitePower563/ylp#2]
Add more pictures and stuff

**Comment by InfinitePower563** [comment]
added every single triage label because funny xd halal

**Comment by InfinitePower563** [comment]
- Add favicon
- Add more info
- Release basicsecureform v1.2.39

**Comment by InfinitePower563** [comment]
Create separate project for basicsecureform w/ query string [using js](https://flaviocopes.com/urlsearchparams/) and improve transaction page

**Comment by InfinitePower563** [comment]
also add a loading bar to reduce customer complaints

**Comment by Mainakibe** [comment]
Hello can I take this issue?

**Comment by InfinitePower563** [comment]
I got it

**Comment by InfinitePower563** [comment]
branch enhancements created. closing because this is now just a reference
